;application
application.cache_config=1 
application.directory={&$APP_PATH&}
;application.library代表应用本地类所在的路径
application.library={&$ALP&}
application.throwException=0
application.dispatcher.catchException=1
application.modules="Index"   
application.dispatcher.defaultModuel=Index
application.dispatcher.defaultController=Index
application.dispatcher.defaultAction=index
